# Generated by Django 3.0.8 on 2020-07-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200711_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
